language: php
sudo: true
env:
  - NODE_VERSION="14.2.0"
os:
  - linux
php:
  - '7.2'
cache:
  yarn: true
  npm: true
  directories:
    - $HOME/.composer/cache
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq libxslt-dev zip unzip graphviz
  - wget https://github.com/phpDocumentor/phpDocumentor2/files/2310268/phpdoc.7.2.phar.zip
  - unzip phpdoc.7.2.phar.zip
  - php phpdoc\(7.2\).phar -d ./src -t ./docs --ignore vendor/
  # For the sake of semantic-release
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.35.3/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends -y -qq yarn
  - yarn -v
install:
  - yarn install
  - composer install --dev --no-interaction
before_script:
  - mkdir -p build/cov
  - mkdir -p build/logs
script:
  - ./vendor/bin/phpunit --testdox -c phpunit.xml
  - export NEXT_VERSION=$(node .travis/extract_semver.js)
  - echo $NEXT_VERSION
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local-dir: docs
    on:
      branch: master
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      branch: master
      condition: -n "$NEXT_VERSION"